title: Daily Security
email: xazamaxi@protonmail.com
description: >-
  In this blog we're going to solve CTF's & Write Some Software's.My goal is redirect my little knowledge to other people.
baseurl: ''
url: blacknbunny.github.io
twitter_username: 0DAYanc
github_username: blacknbunny
markdown: kramdown
theme: minima
exclude:
 - vendor/bundle/
plugins:
  - jekyll-feed
