title: Daily Security
email: keymap.blind@gmail.com
description: >-
  In this blog we're going to solve CTF's & Write Some Software's.My goal is redirect my little knowledge to other people.
baseurl: ''
url: blacknbunny.github.io
twitter_username: nouser
github_username: nouser
markdown: kramdown
theme: minima
exclude:
 - vendor/bundle/
plugins:
  - jekyll-feed
